### ISSUE TITLE
Permission denied when i change to my Firebase

### ISSUE THREAD

**Issue by jempurich** [davideast/firebase-react-native-sample#10]
FIREBASE WARNING: set at /items/-KOVBqAEv9fhNCyAjiG_ failed: permission_denied

Possible Unhandled Promise Rejection (id: 0): PERMISSION_DENIED: Permission denied

**Comment by davideast** [comment]
You need to set your security rules to read allow public read and write for the tutorial.

**Comment by shaheerakhlaq** [comment]
@davideast how to set security?
