### ISSUE TITLE
createCustomToken not being supported

### ISSUE THREAD

**Issue by adank92** [davideast/firebase-react-native-sample#16]
Hi @davideast,

I was wondering if you know the reason why `createCustomToken` is not supported on react-native, even though it is documented as part of the Node.js SDK https://firebase.google.com/docs/reference/node/firebase.auth.Auth#createCustomToken. It seems that in the past it was possible to create custom tokens by using https://github.com/firebase/firebase-token-generator-node (versions 2.x.x).

Thanks!

**Comment by davideast** [comment]
@adank92 I'm not sure you would want to create tokens on a client device as you would need a service account stored locally and that would not be secure.
