### ISSUE TITLE
Current firebase features that work with React-native

### ISSUE THREAD

**Issue by SanjithKanagavel** [davideast/firebase-react-native-sample#20]
May i know what are the current firebase features that work with react-native app?

I already know that **Authentication**,**Login**,**Realtime Database** work other than it what features work ? Please tell me what features also work ? 

@davideast

**Comment by SanjithKanagavel** [comment]
@davideast @laiso @drmas Please post this on this. Thanks.

**Comment by davideast** [comment]
@SanjithKanagavel Without bridging Database and Auth (non Headful) work. But FireStack has bridged all Native APIs in one nice library: https://github.com/fullstackreact/react-native-firestack

**Comment by SanjithKanagavel** [comment]
Thanks @davideast 👍
