### ISSUE TITLE
Firebase 3.☓ does not work with React native 

### ISSUE THREAD

**Issue by dcworldwide** [davideast/firebase-react-native-sample#3]
Please add 3.x support to RN. My app red screens as soon as I call initializeApp

**Comment by nicovak** [comment]
See https://github.com/davideast/firebase-react-native-sample/issues/4

**Comment by davideast** [comment]
@dcworldwide @nicovak 

Stay tuned, we are working on it!

**Comment by anshulkgupta** [comment]
@davideast any idea on what the timeline is looking like? days/weeks?

**Comment by alexwasner** [comment]
According to the release notes, 3.1.X supports RN. Time to update this @davideast ?

**Comment by davideast** [comment]
@alexwasner @anshulkgupta Yep! I'll be updating this _very soon!_

**Comment by davideast** [comment]
@dcworldwide @anshulkgupta @alexwasner @nicovak Updated!
