### ISSUE TITLE
Firebase constructor

### ISSUE THREAD

**Issue by nicovak** [davideast/firebase-react-native-sample#4]
Hello,

As seen, the firebase API has made some changes:

We don't initialize Firebase with a constructor anymore like so:

index.ios.js

``` javascript
getRef() {
    return new Firebase(FirebaseUrl);
}
```

The correct way to do is  (according to Firebase's documentation):

``` javascript
var firebase = require("firebase");
firebase.initializeApp({
    apiKey: "XXXXX",
    authDomain: "XXXXX",
    databaseURL: "XXXXX",
    storageBucket: "XXXXX",
});
```

But there is still an error: https://github.com/facebook/react-native/issues/7864

**Comment by davideast** [comment]
@nicovak The `new Firebase` call is apart of the old (`< 3.0`) SDK. The current SDK is not yet compatible with React Native, but stay tuned.

I'm closing this issue but follow #3 as the main issue.
