### ISSUE TITLE
`auth().signInWithPopup()` is not working in React Native

### ISSUE THREAD

**Issue by pitzcarraldo** [davideast/firebase-react-native-sample#7]
Hi Firebase.

I'm trying to integrate Firebase 3.1.0 with React Native 0.28.0.
I've implemented some codes that sign in with facebook, but it doesn't work with below error.

![2016-07-17 9 22 37](https://cloud.githubusercontent.com/assets/1966982/16900617/a01b4aac-4c64-11e6-9f99-e2a69eec18b9.png)

I debugged `location.protocol` but it printed `http:`.
This is snippet of my codes.

``` js
function logInWithFacebook(source:?string):ThunkAction {
  return async dispatch => {
    try {
      console.log(location.protocol); // 'http:'
      PROVIDERS.facebook.addScope('public_profile,email,user_friends');
      const { user, credential } = await firebase.auth().signInWithPopup(new firebase.auth.FacebookAuthProvider());
      return dispatch(login(user, credential, source));
    } catch (error) {
      const message = error.message || error;
      alert(message);
      console.warn(message);
    }
  };
}
```

Did I something wrong?
How could I fix this?
Thanks.

**Comment by pitzcarraldo** [comment]
Sorry, I found below article just before from [here](https://firebase.googleblog.com/2016/07/firebase-react-native.html).

> "Headful" auth methods such as signInWithPopup(), signInWithRedirect(), linkWithPopup(), and linkWithRedirect() do not work in React Native (or Cordova, for that matter). You can still sign in or link with a federated provider by using signInWithCredential() with an OAuth token from your provider of choice.

I'll try again with `signInWithCredential`.

**Comment by RFSync** [comment]
Just a side note, if anyone can give a code sample of what signInWithCredential() would look like it would be greatly appreciated. Mainly what would we pass as a credential and where would I retrieve that.

**Comment by jhalborg** [comment]
@myztajay - See [here](https://firebase.google.com/docs/auth/web/facebook-login) under "Advanced"

@davideast - Any plans to incorporate a signInWithPopup() - style method for react native? That would be so awesome! :-) I hate re-building user auth flows, and being able to just call that in a react native app would be fantastic!

**Comment by baseerx** [comment]
I am facing SignInWithPopup is not a function.. i don't know why it is not working while doing authentication with facebook

**Comment by bappyasif** [comment]
That's because Firebase for RN doesn't support those methods. Check this [link](https://firebase.blog/posts/2016/07/firebase-react-native)

you can also check this SO thread https://stackoverflow.com/questions/71026130/react-native-google-authentication-not-working-typeerror-0-auth-signinwith

happy coding :)
