### ISSUE TITLE
Disk Persistence capability in react-native

### ISSUE THREAD

**Issue by sgong-pdftron** [davideast/firebase-react-native-sample#8]
Is there equivalent of "[Firebase defaultConfig].persistenceEnabled = YES;" or "Firebase.getDefaultConfig().setPersistenceEnabled(true);" on react-native? How to avoid having to re-download the data after the app is quit and re-started? Thanks!

**Comment by davideast** [comment]
@sgong90 This is not available in the JS version of the SDK. You can attempt to wrap the native SDK but we have no guidance for doing so.
