### ISSUE TITLE
Best practice for storing and accessing Firebase config across entire app

### ISSUE THREAD

**Issue by kcfgl** [davideast/firebase-react-native-sample#9]
This is actually a question and not an issue, but hopefully one applicable to the broader community.  This sample is awesome, but its built around the concept of a single page. 

For apps that are going to access firebase from numerous views - login, account page, details page, etc - what is the Firebase team's recommendation on the best practice for storing the config and initializing the app?  I can't imagine we would duplicate that code on every page looking to access Firebase.

Thanks!

**Comment by davideast** [comment]
Initialize the app and then export it.

``` js
import * as firebase from 'firebase';

const config = {
 // config values
};
export firebase.initializeApp(config);
```

Then in your other views/components:

``` js
import { app } from './config.js';

class MyComponent extends Component {

   componentDidMount() {
      app.database().ref().child('data').on('value', () => console.log(snap.val()));
   }

}
```

**Comment by stardev24** [comment]
Hi @davideast,

How can we store this in a secure way with react native app?I feel storing config as is may not be secure.Please advice.

Thanks,
Sai
